version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez which has row per product_id found on orders_id
        loaded_at_field: "CAST (date_date AS TIMESTAMP)"
        freshness: 
          warn_after: {count: 90, period: day} 
        columns:
          - name: date_date
      - name: product
        identifier: raw_gz_product
        description: product information of Greenweez
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: shipping information and cost of Greenweez
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: ads data from google adwords
      - name: criteo
        identifier: raw_gz_criteo
        description: ads data from criteo
      - name: facebook
        identifier: raw_gz_facebook
        description: ads data from facebook
      - name: bing
        identifier: raw_gz_bing
        description: ads data from bing


# test example for int_sales_margin models and its documentation

models:
   # Staging #
   # ...snip...

   # Intermediate #
   - name: int_orders_margin
     description: margin calculation per order
     columns:
       - name: orders_id
         description: primary key
         tests:
           - unique
           - not_null
       - name: margin
         description: margin = revenue - purchase_cost
         tests:
           - not_null
       - name: Purchase_cost
         description: purchase_cost = quantity * purchase_price
         tests:
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null

   - name: int_sales_margin
     description: margin calculation per order line / product sales
     columns:
       - name: orders_id
         description: orders key
         tests:
           - not_null
       - name: products_id
         description: products key
         tests:
           - not_null
       - name: margin
         description: margin = revenue - purchase_cost
         tests:
           - not_null
       - name: Purchase_cost
         description: purchase_cost = quantity * purchase_price
         tests:
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
     tests:
       - unique:
           column_name: "(orders_id || '-' || products_id)"

   - name: int_orders_operational
     description: operational margin calculation per order
     columns:
       - name: orders_id
         description: primary key
         tests:
           - unique
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: operational_margin
         description: operational_margin = margin + shipping_fee - log_cost - ship_cost
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: purchase_cost
         description: purchase_cost = quantity * purchase_price
         tests:
           - not_null
       - name: margin
         description: margin = revenue - purchase_cost
         tests:
           - not_null
       - name: shipping_fee
         description: the price the customer pays for shipping
       - name: log_cost
         description: the cost of preparing the parcel in the distribution centre/warehouse
       - name: ship_cost
         description: shipping cost paid by Greenweez to the carrier/logistics provider